// Copyright (c) 2019-2026 ReactiveUI and Contributors. All rights reserved.
// ReactiveUI and Contributors licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.
using System.Text.Json.Serialization;

namespace Refit;

/// <summary>The object representing the details about a ValidationException caught by a service implementing RFC 7807.</summary>
public class ProblemDetails
{
    /// <summary>Gets the collection of resulting errors for the request.</summary>
    public Dictionary<string, string[]> Errors { get; init; } = [];

    /// <summary>Gets the collection of ProblemDetails extensions.</summary>
    [JsonExtensionData]
    public IDictionary<string, object> Extensions { get; init; } =
        new Dictionary<string, object>(StringComparer.Ordinal);

    /// <summary>Gets or sets a URI reference that identifies the problem type.</summary>
    public string? Type { get; set; } = "about:blank";

    /// <summary>Gets or sets a short, human-readable summary of the problem type.</summary>
    public string? Title { get; set; }

    /// <summary>Gets or sets the HTTP status code generated by the origin server for this occurrence of the problem.</summary>
    public int Status { get; set; }

    /// <summary>Gets or sets a human-readable explanation specific to this occurrence of the problem.</summary>
    public string? Detail { get; set; }

    /// <summary>Gets or sets a URI reference that identifies the specific occurrence of the problem.</summary>
    public string? Instance { get; set; }
}
