// Copyright (c) 2019-2026 ReactiveUI and Contributors. All rights reserved.
// ReactiveUI and Contributors licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.
using System.Diagnostics.CodeAnalysis;

namespace Refit;

/// <summary>
/// Provides static methods for creating request builders for Refit interface types. This class enables the
/// generation of strongly-typed HTTP client implementations based on interface definitions and optional settings.
/// </summary>
/// <remarks>Request builders generated by this class use reflection to analyze the provided interface
/// type and create implementations for HTTP API calls. When using trimming or linking, ensure that referenced
/// interfaces and data transfer objects are preserved, as reflection is required for correct operation. All members
/// of this class are thread-safe and can be used concurrently across multiple threads.</remarks>
public static class RequestBuilder
{
    /// <summary>The platform request builder factory used to create builders.</summary>
    private static readonly RequestBuilderFactory _platformRequestBuilderFactory = new();

    /// <summary>Creates an HTTP request builder for the specified interface type.</summary>
    /// <remarks>Use this method to obtain a request builder for a given API interface, typically for
    /// advanced scenarios such as custom client generation or integration with dependency injection. The returned
    /// builder can be used to create HTTP requests corresponding to the methods defined on the interface.</remarks>
    /// <typeparam name="T">The interface type that defines the HTTP API methods to be implemented by the request builder. Must be an
    /// interface.</typeparam>
    /// <param name="settings">The Refit settings to use for configuring the request builder. May be null to use default settings.</param>
    /// <returns>An instance of IRequestBuilder T that can be used to construct HTTP requests for the specified interface
    /// type.</returns>
    [SuppressMessage(
        "Major Code Smell",
        "S4018:Generic methods should provide type parameters",
        Justification = "Type parameter intentionally specified explicitly by callers.")]
    [RequiresUnreferencedCode("Building requests from reflected interface methods requires interface and request object metadata to be available at runtime.")]
    public static IRequestBuilder<T> ForType<
        [DynamicallyAccessedMembers(
            DynamicallyAccessedMemberTypes.Interfaces |
            DynamicallyAccessedMemberTypes.PublicMethods |
            DynamicallyAccessedMemberTypes.NonPublicMethods)]
    T>(RefitSettings? settings) =>
        _platformRequestBuilderFactory.Create<T>(settings);

    /// <summary>Creates a request builder for the specified type, enabling construction of requests against its members.</summary>
    /// <typeparam name="T">The type for which to create the request builder. This type's methods will be available for request
    /// construction.</typeparam>
    /// <returns>An object that can be used to build requests for the specified type.</returns>
    [SuppressMessage(
        "Major Code Smell",
        "S4018:Generic methods should provide type parameters",
        Justification = "Type parameter intentionally specified explicitly by callers.")]
    [RequiresUnreferencedCode("Building requests from reflected interface methods requires interface and request object metadata to be available at runtime.")]
    public static IRequestBuilder<T> ForType<
        [DynamicallyAccessedMembers(
            DynamicallyAccessedMemberTypes.Interfaces |
            DynamicallyAccessedMemberTypes.PublicMethods |
            DynamicallyAccessedMemberTypes.NonPublicMethods)]
    T>() =>
        _platformRequestBuilderFactory.Create<T>(null);

    /// <summary>Creates an implementation of the specified Refit interface for making HTTP requests.</summary>
    /// <remarks>The returned IRequestBuilder uses reflection to analyze the provided interface type.
    /// When using trimming or linking, ensure that all referenced interfaces and data transfer objects are
    /// preserved to avoid runtime errors.</remarks>
    /// <param name="refitInterfaceType">The interface type that defines the HTTP API contract. Must be a non-generic interface decorated with Refit
    /// attributes.</param>
    /// <param name="settings">Optional settings to customize the behavior of the generated request builder. If null, default settings are
    /// used.</param>
    /// <returns>An IRequestBuilder instance that can be used to construct HTTP requests for the specified interface.</returns>
    [RequiresUnreferencedCode("Building requests from reflected interface methods requires interface and request object metadata to be available at runtime.")]
    public static IRequestBuilder ForType(
        [DynamicallyAccessedMembers(
            DynamicallyAccessedMemberTypes.Interfaces |
            DynamicallyAccessedMemberTypes.PublicMethods |
            DynamicallyAccessedMemberTypes.NonPublicMethods)]
        Type refitInterfaceType,
        RefitSettings? settings) =>
        new CachedRequestBuilderImplementation(
            new RequestBuilderImplementation(refitInterfaceType, settings));

    /// <summary>Creates an instance of an IRequestBuilder for the specified Refit interface type.</summary>
    /// <remarks>The specified interface type must be decorated with Refit attributes to define the
    /// API endpoints. If trimming is enabled, ensure that all referenced interfaces and data transfer objects are
    /// preserved, as reflection is used to analyze the interface methods.</remarks>
    /// <param name="refitInterfaceType">The interface type that defines the Refit API contract. Must be a non-generic interface decorated with Refit
    /// attributes.</param>
    /// <returns>An IRequestBuilder instance that can be used to construct HTTP requests for the specified interface type.</returns>
    [RequiresUnreferencedCode("Building requests from reflected interface methods requires interface and request object metadata to be available at runtime.")]
    public static IRequestBuilder ForType(
        [DynamicallyAccessedMembers(
            DynamicallyAccessedMemberTypes.Interfaces |
            DynamicallyAccessedMemberTypes.PublicMethods |
            DynamicallyAccessedMemberTypes.NonPublicMethods)]
        Type refitInterfaceType) =>
        ForType(refitInterfaceType, null);
}
