version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: weekly
    time: "00:00"
  open-pull-requests-limit: 20
  
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    time: "00:00"
  open-pull-requests-limit: 20  
