//HintName: INestedGitHubApi.g.cs
// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

namespace Refit.Implementation
{
    /// <summary>Contains generated Refit implementation types.</summary>
    internal partial class Generated
    {
        /// <summary>Generated Refit implementation for global::Refit.Tests.TestNested.INestedGitHubApi.</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("InterfaceStubGeneratorV2", "11.0.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.Diagnostics.DebuggerNonUserCode]
        [global::RefitInternalGenerated.PreserveAttribute]
        [global::System.Reflection.Obfuscation(Exclude=true)]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        private sealed class RefitTestsTestNestedINestedGitHubApi
            : global::Refit.Tests.TestNested.INestedGitHubApi
        {
            /// <summary>The request builder used to create Refit method delegates.</summary>
            private readonly global::Refit.IRequestBuilder? _requestBuilder;

            /// <summary>The settings used by this generated Refit implementation.</summary>
            private readonly global::Refit.RefitSettings _settings;

            /// <summary>Gets the HTTP client used by this generated Refit implementation.</summary>
            public global::System.Net.Http.HttpClient Client { get; }

            /// <summary>Initializes a new instance of the RefitTestsTestNestedINestedGitHubApi class.</summary>
            /// <param name="client">The HTTP client used by the generated implementation.</param>
            /// <param name="requestBuilder">The request builder used to create Refit method delegates.</param>
            public RefitTestsTestNestedINestedGitHubApi(global::System.Net.Http.HttpClient client, global::Refit.IRequestBuilder requestBuilder)
            {
                Client = client;
                _requestBuilder = requestBuilder;
                _settings = requestBuilder.Settings;
            }


            /// <summary>Cached parameter type array for the generated GetUser method.</summary>
            private static readonly global::System.Type[] ______typeParameters = new global::System.Type[] { typeof(string) };
            /// <inheritdoc />
            public async global::System.Threading.Tasks.Task<global::Refit.Tests.User> GetUser(string @userName)
            {
                var refitArguments = new object[] { @userName };
                var refitRequestBuilder = _requestBuilder ?? throw new global::System.InvalidOperationException("This generated Refit method requires a request builder.");
                var refitFunc = refitRequestBuilder.BuildRestResultFuncForMethod("GetUser", ______typeParameters );

                return await ((global::System.Threading.Tasks.Task<global::Refit.Tests.User>)refitFunc(this.Client, refitArguments)).ConfigureAwait(false);
            }


            /// <summary>Cached parameter type array for the generated GetUserObservable method.</summary>
            private static readonly global::System.Type[] ______typeParameters0 = new global::System.Type[] { typeof(string) };
            /// <inheritdoc />
            public global::System.IObservable<global::Refit.Tests.User> GetUserObservable(string @userName)
            {
                var refitArguments = new object[] { @userName };
                var refitRequestBuilder = _requestBuilder ?? throw new global::System.InvalidOperationException("This generated Refit method requires a request builder.");
                var refitFunc = refitRequestBuilder.BuildRestResultFuncForMethod("GetUserObservable", ______typeParameters0 );

                return (global::System.IObservable<global::Refit.Tests.User>)refitFunc(this.Client, refitArguments);
            }


            /// <summary>Cached parameter type array for the generated GetUserCamelCase method.</summary>
            private static readonly global::System.Type[] ______typeParameters1 = new global::System.Type[] { typeof(string) };
            /// <inheritdoc />
            public global::System.IObservable<global::Refit.Tests.User> GetUserCamelCase(string @userName)
            {
                var refitArguments = new object[] { @userName };
                var refitRequestBuilder = _requestBuilder ?? throw new global::System.InvalidOperationException("This generated Refit method requires a request builder.");
                var refitFunc = refitRequestBuilder.BuildRestResultFuncForMethod("GetUserCamelCase", ______typeParameters1 );

                return (global::System.IObservable<global::Refit.Tests.User>)refitFunc(this.Client, refitArguments);
            }


            /// <summary>Cached parameter type array for the generated GetOrgMembers method.</summary>
            private static readonly global::System.Type[] ______typeParameters2 = new global::System.Type[] { typeof(string) };
            /// <inheritdoc />
            public async global::System.Threading.Tasks.Task<global::System.Collections.Generic.List<global::Refit.Tests.User>> GetOrgMembers(string @orgName)
            {
                var refitArguments = new object[] { @orgName };
                var refitRequestBuilder = _requestBuilder ?? throw new global::System.InvalidOperationException("This generated Refit method requires a request builder.");
                var refitFunc = refitRequestBuilder.BuildRestResultFuncForMethod("GetOrgMembers", ______typeParameters2 );

                return await ((global::System.Threading.Tasks.Task<global::System.Collections.Generic.List<global::Refit.Tests.User>>)refitFunc(this.Client, refitArguments)).ConfigureAwait(false);
            }


            /// <summary>Cached parameter type array for the generated FindUsers method.</summary>
            private static readonly global::System.Type[] ______typeParameters3 = new global::System.Type[] { typeof(string) };
            /// <inheritdoc />
            public async global::System.Threading.Tasks.Task<global::Refit.Tests.UserSearchResult> FindUsers(string @q)
            {
                var refitArguments = new object[] { @q };
                var refitRequestBuilder = _requestBuilder ?? throw new global::System.InvalidOperationException("This generated Refit method requires a request builder.");
                var refitFunc = refitRequestBuilder.BuildRestResultFuncForMethod("FindUsers", ______typeParameters3 );

                return await ((global::System.Threading.Tasks.Task<global::Refit.Tests.UserSearchResult>)refitFunc(this.Client, refitArguments)).ConfigureAwait(false);
            }

            /// <inheritdoc />
            public global::System.Threading.Tasks.Task<global::System.Net.Http.HttpResponseMessage> GetIndex()
            {
                var refitSettings = _settings;
                var refitRequest = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Get, global::Refit.GeneratedRequestRunner.BuildRelativeUri(this.Client, "/", refitSettings.UrlResolution));
                #if NET6_0_OR_GREATER
                refitRequest.Version = refitSettings.Version;
                refitRequest.VersionPolicy = refitSettings.VersionPolicy;
                #endif
                global::Refit.GeneratedRequestRunner.SetHeader(refitRequest, "User-Agent", "Refit Integration Tests");
                global::Refit.GeneratedRequestRunner.AddConfiguredRequestOptions(refitRequest, refitSettings, typeof(global::Refit.Tests.TestNested.INestedGitHubApi));
                return global::Refit.GeneratedRequestRunner.SendAsync<global::System.Net.Http.HttpResponseMessage, global::System.Net.Http.HttpResponseMessage>(
                    this.Client,
                    refitRequest,
                    refitSettings,
                    false,
                    false,
                    false,
                    global::System.Threading.CancellationToken.None);
            }

            /// <inheritdoc />
            public global::System.IObservable<string> GetIndexObservable()
            {
                var refitArguments = global::System.Array.Empty<object>();
                var refitRequestBuilder = _requestBuilder ?? throw new global::System.InvalidOperationException("This generated Refit method requires a request builder.");
                var refitFunc = refitRequestBuilder.BuildRestResultFuncForMethod("GetIndexObservable", global::System.Array.Empty<global::System.Type>() );

                return (global::System.IObservable<string>)refitFunc(this.Client, refitArguments);
            }

            /// <inheritdoc />
            public global::System.Threading.Tasks.Task NothingToSeeHere()
            {
                var refitSettings = _settings;
                var refitRequest = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Get, global::Refit.GeneratedRequestRunner.BuildRelativeUri(this.Client, "/give-me-some-404-action", refitSettings.UrlResolution));
                #if NET6_0_OR_GREATER
                refitRequest.Version = refitSettings.Version;
                refitRequest.VersionPolicy = refitSettings.VersionPolicy;
                #endif
                global::Refit.GeneratedRequestRunner.SetHeader(refitRequest, "User-Agent", "Refit Integration Tests");
                global::Refit.GeneratedRequestRunner.AddConfiguredRequestOptions(refitRequest, refitSettings, typeof(global::Refit.Tests.TestNested.INestedGitHubApi));
                return global::Refit.GeneratedRequestRunner.SendVoidAsync(
                    this.Client,
                    refitRequest,
                    refitSettings,
                    false,
                    global::System.Threading.CancellationToken.None);
            }
        }
    }
}
