//HintName: IGeneratedInterface.g.cs
// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

namespace Refit.Implementation
{
    /// <summary>Contains generated Refit implementation types.</summary>
    internal partial class Generated
    {
        /// <summary>Generated Refit implementation for global::IGeneratedInterface&lt;T1, T2, T3, T4, T5&gt;.</summary>
        /// <typeparam name="T1">The generated interface type parameter.</typeparam>
        /// <typeparam name="T2">The generated interface type parameter.</typeparam>
        /// <typeparam name="T3">The generated interface type parameter.</typeparam>
        /// <typeparam name="T4">The generated interface type parameter.</typeparam>
        /// <typeparam name="T5">The generated interface type parameter.</typeparam>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("InterfaceStubGeneratorV2", "11.0.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.Diagnostics.DebuggerNonUserCode]
        [global::RefitInternalGenerated.PreserveAttribute]
        [global::System.Reflection.Obfuscation(Exclude=true)]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        private sealed class IGeneratedInterface<T1, T2, T3, T4, T5>
            : global::IGeneratedInterface<T1, T2, T3, T4, T5>
        where T1 : class
        where T2 : unmanaged
        where T3 : struct
        where T4 : notnull
        where T5 : class, global::System.IDisposable, new()
        {
            /// <summary>The request builder used to create Refit method delegates.</summary>
            private readonly global::Refit.IRequestBuilder _requestBuilder;

            /// <summary>Gets the HTTP client used by this generated Refit implementation.</summary>
            public global::System.Net.Http.HttpClient Client { get; }

            /// <summary>Initializes a new instance of the IGeneratedInterface class.</summary>
            /// <param name="client">The HTTP client used by the generated implementation.</param>
            /// <param name="requestBuilder">The request builder used to create Refit method delegates.</param>
            public IGeneratedInterface(global::System.Net.Http.HttpClient client, global::Refit.IRequestBuilder requestBuilder)
            {
                Client = client;
                _requestBuilder = requestBuilder;
            }

            /// <inheritdoc />
            public global::System.Threading.Tasks.Task<string> Get()
            {
                var refitSettings = _requestBuilder.Settings;
                var refitBasePath = this.Client.BaseAddress?.AbsolutePath ?? throw new global::System.InvalidOperationException("BaseAddress must be set on the HttpClient instance");
                refitBasePath = refitBasePath == "/" ? string.Empty : refitBasePath.TrimEnd('/');
                var refitRequest = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Get, new global::System.Uri(refitBasePath + "/users", global::System.UriKind.Relative));
                #if NET6_0_OR_GREATER
                refitRequest.Version = refitSettings.Version;
                refitRequest.VersionPolicy = refitSettings.VersionPolicy;
                #endif
                global::Refit.GeneratedRequestRunner.AddConfiguredRequestOptions(refitRequest, refitSettings, typeof(global::IGeneratedInterface<T1, T2, T3, T4, T5>));
                return global::Refit.GeneratedRequestRunner.SendAsync<string, string>(
                    this.Client,
                    refitRequest,
                    refitSettings,
                    false,
                    true,
                    false,
                    global::System.Threading.CancellationToken.None);
            }
        }
    }
}
