//HintName: IGeneratedClient.g.cs
// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

namespace Refit.Implementation
{
    /// <summary>Contains generated Refit implementation types.</summary>
    internal partial class GeneratedCompilation
    {
        /// <summary>Generated Refit implementation for global::RefitGeneratorTest.IGeneratedClient.</summary>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.Diagnostics.DebuggerNonUserCode]
        [global::RefitInternalGenerated.Compilation.PreserveAttribute]
        [global::System.Reflection.Obfuscation(Exclude=true)]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        private sealed class RefitGeneratorTestIGeneratedClient
            : global::RefitGeneratorTest.IGeneratedClient
        {
            /// <summary>The request builder used to create Refit method delegates.</summary>
            private readonly global::Refit.IRequestBuilder? _requestBuilder;

            /// <summary>The settings used by this generated Refit implementation.</summary>
            private readonly global::Refit.RefitSettings _settings;

            /// <summary>Gets the HTTP client used by this generated Refit implementation.</summary>
            public global::System.Net.Http.HttpClient Client { get; }

            /// <summary>Initializes a new instance of the RefitGeneratorTestIGeneratedClient class.</summary>
            /// <param name="client">The HTTP client used by the generated implementation.</param>
            /// <param name="requestBuilder">The request builder used to create Refit method delegates.</param>
            public RefitGeneratorTestIGeneratedClient(global::System.Net.Http.HttpClient client, global::Refit.IRequestBuilder requestBuilder)
            {
                Client = client;
                _requestBuilder = requestBuilder;
                _settings = requestBuilder.Settings;
            }

            /// <summary>Initializes a new instance of the RefitGeneratorTestIGeneratedClient class for generated-only execution.</summary>
            /// <param name="client">The HTTP client used by the generated implementation.</param>
            /// <param name="settings">The settings used by the generated implementation.</param>
            public RefitGeneratorTestIGeneratedClient(global::System.Net.Http.HttpClient client, global::Refit.RefitSettings settings)
            {
                Client = client;
                _settings = settings;
            }
            /// <summary>Cached attribute provider for the generated BuildRefitListPageRequest method's token parameter.</summary>
            private static readonly global::System.Reflection.ICustomAttributeProvider ______tokenAttributeProvider = new global::Refit.GeneratedParameterAttributeProvider(new global::System.Collections.Generic.Dictionary<global::System.Type, object[]>() {{ typeof(global::Refit.PageTokenAttribute), new object[] { new global::Refit.PageTokenAttribute()} }, { typeof(global::Refit.AliasAsAttribute), new object[] { new global::Refit.AliasAsAttribute("continuation-token")} }});

            /// <inheritdoc />
            public global::System.Net.Http.HttpRequestMessage BuildRefitListPageRequest(string @bucket, string? @prefix, string? @token)
            {
                var refitSettings = _settings;
                var refitUseDefaultFormatting = global::Refit.GeneratedRequestRunner.UsesDefaultUrlParameterFormatting(refitSettings);
                var refitQueryBuilder = new global::Refit.GeneratedQueryStringBuilder(global::Refit.GeneratedRequestRunner.BuildRequestPath(
                            "/{bucket}",
                            refitSettings.AllowUnmatchedRouteParameters,
                            [((1, 9), refitUseDefaultFormatting ? (@bucket) : global::Refit.GeneratedRequestRunner.FormatUrlParameter(refitSettings, @bucket, global::Refit.GeneratedParameterAttributeProvider.Empty, typeof(string)))]), false);
                if (@prefix != null)
                {
                    refitQueryBuilder.AddPreEscapedKey("prefix", refitUseDefaultFormatting ? (@prefix) : global::Refit.GeneratedRequestRunner.FormatUrlParameter(refitSettings, @prefix, global::Refit.GeneratedParameterAttributeProvider.Empty, typeof(string)), false);
                }
                if (@token != null)
                {
                    refitQueryBuilder.AddPreEscapedKey("continuation-token", refitUseDefaultFormatting ? (@token) : global::Refit.GeneratedRequestRunner.FormatUrlParameter(refitSettings, @token, ______tokenAttributeProvider, typeof(string)), false);
                }
                var refitRequest = new global::System.Net.Http.HttpRequestMessage(
                    global::System.Net.Http.HttpMethod.Get,
                    global::Refit.GeneratedRequestRunner.BuildRelativeUri(
                        this.Client,
                        refitQueryBuilder.Build(),
                        refitSettings.UrlResolution)
                );
                global::Refit.GeneratedRequestRunner.AddConfiguredRequestOptions(refitRequest, refitSettings, typeof(global::RefitGeneratorTest.IGeneratedClient));
                global::Refit.GeneratedRequestRunner.AddRequestProperty<string>(refitRequest, global::Refit.HttpRequestMessageOptions.MethodName, "List");
                global::Refit.GeneratedRequestRunner.AddRequestProperty<string>(refitRequest, global::Refit.HttpRequestMessageOptions.RelativePathTemplate, "/{bucket}");
                if (refitSettings.CaptureMethodArguments) { global::Refit.GeneratedRequestRunner.AddRequestProperty<object?[]>(refitRequest, global::Refit.HttpRequestMessageOptions.MethodArguments, new object?[] { @bucket, @prefix, @token }); }
                return refitRequest;
            }

            /// <inheritdoc />
            public global::Refit.PagedEnumerable<global::RefitGeneratorTest.IGeneratedClient.ObjectPage, global::RefitGeneratorTest.IGeneratedClient.StoredObject> List(string @bucket, string? @prefix, string? @token)
            {
                var refitSettings = _settings;
                return global::Refit.PagedEnumerable.Create<global::RefitGeneratorTest.IGeneratedClient.ObjectPage, global::RefitGeneratorTest.IGeneratedClient.StoredObject, string>(
                    @token,
                    (refitPageToken, refitPageCancellation) => global::Refit.GeneratedRequestRunner.SendAsync<global::RefitGeneratorTest.IGeneratedClient.ObjectPage, global::RefitGeneratorTest.IGeneratedClient.ObjectPage>(
                        this.Client,
                        this.BuildRefitListPageRequest(@bucket, @prefix, refitPageToken),
                        refitSettings,
                        false,
                        true,
                        false,
                        refitPageCancellation),
                    static refitPage => refitPage.@Contents,
                    static (refitPage, _) => global::Refit.PageContinuation.To<string>(refitPage.@NextToken));
            }
        }
    }
}
