//HintName: IGeneratedClient.g.cs
// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

namespace Refit.Implementation
{
    /// <summary>Contains generated Refit implementation types.</summary>
    internal partial class GeneratedCompilation
    {
        /// <summary>Generated Refit implementation for global::RefitGeneratorTest.IGeneratedClient.</summary>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.Diagnostics.DebuggerNonUserCode]
        [global::RefitInternalGenerated.Compilation.PreserveAttribute]
        [global::System.Reflection.Obfuscation(Exclude=true)]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        private sealed class RefitGeneratorTestIGeneratedClient
            : global::RefitGeneratorTest.IGeneratedClient
        {
            /// <summary>The request builder used to create Refit method delegates.</summary>
            private readonly global::Refit.IRequestBuilder? _requestBuilder;

            /// <summary>The settings used by this generated Refit implementation.</summary>
            private readonly global::Refit.RefitSettings _settings;

            /// <summary>Gets the HTTP client used by this generated Refit implementation.</summary>
            public global::System.Net.Http.HttpClient Client { get; }

            /// <summary>Initializes a new instance of the RefitGeneratorTestIGeneratedClient class.</summary>
            /// <param name="client">The HTTP client used by the generated implementation.</param>
            /// <param name="requestBuilder">The request builder used to create Refit method delegates.</param>
            public RefitGeneratorTestIGeneratedClient(global::System.Net.Http.HttpClient client, global::Refit.IRequestBuilder requestBuilder)
            {
                Client = client;
                _requestBuilder = requestBuilder;
                _settings = requestBuilder.Settings;
            }

            /// <summary>Initializes a new instance of the RefitGeneratorTestIGeneratedClient class for generated-only execution.</summary>
            /// <param name="client">The HTTP client used by the generated implementation.</param>
            /// <param name="settings">The settings used by the generated implementation.</param>
            public RefitGeneratorTestIGeneratedClient(global::System.Net.Http.HttpClient client, global::Refit.RefitSettings settings)
            {
                Client = client;
                _settings = settings;
            }
            /// <summary>Cached attribute provider for the generated BuildRefitSearchPageRequest method's startAt parameter.</summary>
            private static readonly global::System.Reflection.ICustomAttributeProvider ______startAtAttributeProvider = new global::Refit.GeneratedParameterAttributeProvider(new global::System.Collections.Generic.Dictionary<global::System.Type, object[]>() {{ typeof(global::Refit.PageTokenAttribute), new object[] { new global::Refit.PageTokenAttribute()} }, { typeof(global::Refit.AliasAsAttribute), new object[] { new global::Refit.AliasAsAttribute("startAt")} }});

            /// <inheritdoc />
            public global::System.Net.Http.HttpRequestMessage BuildRefitSearchPageRequest(string @jql, int @startAt)
            {
                var refitSettings = _settings;
                var refitUseDefaultFormatting = global::Refit.GeneratedRequestRunner.UsesDefaultUrlParameterFormatting(refitSettings);
                var refitQueryBuilder = new global::Refit.GeneratedQueryStringBuilder("/search", false);
                if (@jql != null)
                {
                    refitQueryBuilder.AddPreEscapedKey("jql", refitUseDefaultFormatting ? (@jql) : global::Refit.GeneratedRequestRunner.FormatUrlParameter(refitSettings, @jql, global::Refit.GeneratedParameterAttributeProvider.Empty, typeof(string)), false);
                }
                if (refitUseDefaultFormatting)
                {
                    refitQueryBuilder.AddFormattedPreEscapedKey("startAt", @startAt, null, false);
                }
                else
                {
                    refitQueryBuilder.AddPreEscapedKey("startAt", global::Refit.GeneratedRequestRunner.FormatUrlParameter(refitSettings, @startAt, ______startAtAttributeProvider, typeof(int)), false);
                }
                var refitRequest = new global::System.Net.Http.HttpRequestMessage(
                    global::System.Net.Http.HttpMethod.Get,
                    global::Refit.GeneratedRequestRunner.BuildRelativeUri(
                        this.Client,
                        refitQueryBuilder.Build(),
                        refitSettings.UrlResolution)
                );
                global::Refit.GeneratedRequestRunner.AddConfiguredRequestOptions(refitRequest, refitSettings, typeof(global::RefitGeneratorTest.IGeneratedClient));
                global::Refit.GeneratedRequestRunner.AddRequestProperty<string>(refitRequest, global::Refit.HttpRequestMessageOptions.MethodName, "Search");
                global::Refit.GeneratedRequestRunner.AddRequestProperty<string>(refitRequest, global::Refit.HttpRequestMessageOptions.RelativePathTemplate, "/search");
                if (refitSettings.CaptureMethodArguments) { global::Refit.GeneratedRequestRunner.AddRequestProperty<object?[]>(refitRequest, global::Refit.HttpRequestMessageOptions.MethodArguments, new object?[] { @jql, @startAt }); }
                return refitRequest;
            }

            /// <inheritdoc />
            public global::Refit.PagedEnumerable<global::RefitGeneratorTest.IGeneratedClient.IssuePage, global::RefitGeneratorTest.IGeneratedClient.Issue> Search(string @jql, int @startAt)
            {
                var refitSettings = _settings;
                return global::Refit.PagedEnumerable.Create<global::RefitGeneratorTest.IGeneratedClient.IssuePage, global::RefitGeneratorTest.IGeneratedClient.Issue, int>(
                    @startAt,
                    (refitPageToken, refitPageCancellation) => global::Refit.GeneratedRequestRunner.SendAsync<global::RefitGeneratorTest.IGeneratedClient.IssuePage, global::RefitGeneratorTest.IGeneratedClient.IssuePage>(
                        this.Client,
                        this.BuildRefitSearchPageRequest(@jql, refitPageToken),
                        refitSettings,
                        false,
                        true,
                        false,
                        refitPageCancellation),
                    static refitPage => refitPage.@Issues,
                    static (refitPage, refitPageToken) => global::Refit.GeneratedPaging.NextOffset<global::RefitGeneratorTest.IGeneratedClient.Issue>(refitPageToken, refitPage.@Issues, refitPage.@Total));
            }
        }
    }
}
