//HintName: IGeneratedClient.g.cs
// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

namespace Refit.Implementation
{
    /// <summary>Contains generated Refit implementation types.</summary>
    internal partial class Generated
    {
        /// <summary>Generated Refit implementation for global::RefitGeneratorTest.IGeneratedClient.</summary>
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.Diagnostics.DebuggerNonUserCode]
        [global::RefitInternalGenerated.PreserveAttribute]
        [global::System.Reflection.Obfuscation(Exclude=true)]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        private sealed class RefitGeneratorTestIGeneratedClient
            : global::RefitGeneratorTest.IGeneratedClient
        {
            /// <summary>The request builder used to create Refit method delegates.</summary>
            private readonly global::Refit.IRequestBuilder? _requestBuilder;

            /// <summary>The settings used by this generated Refit implementation.</summary>
            private readonly global::Refit.RefitSettings _settings;

            /// <summary>Gets the HTTP client used by this generated Refit implementation.</summary>
            public global::System.Net.Http.HttpClient Client { get; }

            /// <summary>Initializes a new instance of the RefitGeneratorTestIGeneratedClient class.</summary>
            /// <param name="client">The HTTP client used by the generated implementation.</param>
            /// <param name="requestBuilder">The request builder used to create Refit method delegates.</param>
            public RefitGeneratorTestIGeneratedClient(global::System.Net.Http.HttpClient client, global::Refit.IRequestBuilder requestBuilder)
            {
                Client = client;
                _requestBuilder = requestBuilder;
                _settings = requestBuilder.Settings;
            }

            /// <summary>Initializes a new instance of the RefitGeneratorTestIGeneratedClient class for generated-only execution.</summary>
            /// <param name="client">The HTTP client used by the generated implementation.</param>
            /// <param name="settings">The settings used by the generated implementation.</param>
            public RefitGeneratorTestIGeneratedClient(global::System.Net.Http.HttpClient client, global::Refit.RefitSettings settings)
            {
                Client = client;
                _settings = settings;
            }
            /// <summary>Cached attribute provider for the generated GetUser method's user parameter.</summary>
            private static readonly global::Refit.GeneratedParameterAttributeProvider ______userAttributeProvider = global::Refit.GeneratedParameterAttributeProvider.Empty;

            /// <inheritdoc />
            public global::System.IObservable<global::System.Net.Http.HttpResponseMessage> GetUser(string @user)
            {
                var refitSettings = _settings;
                global::System.Net.Http.HttpRequestMessage BuildRefitRequest()
                {
                var refitUseDefaultFormatting = global::Refit.GeneratedRequestRunner.UsesDefaultUrlParameterFormatting(refitSettings);
                var refitRequest = new global::System.Net.Http.HttpRequestMessage(global::System.Net.Http.HttpMethod.Get, global::Refit.GeneratedRequestRunner.BuildRelativeUri(this.Client, global::Refit.GeneratedRequestRunner.BuildRequestPath("/users/{user}", refitSettings.AllowUnmatchedRouteParameters, [((7, 13), refitUseDefaultFormatting ? (@user) : refitSettings.UrlParameterFormatter.Format(@user, ______userAttributeProvider, typeof(string)))]), refitSettings.UrlResolution));
                global::Refit.GeneratedRequestRunner.AddConfiguredRequestOptions(refitRequest, refitSettings, typeof(global::RefitGeneratorTest.IGeneratedClient));
                    return refitRequest;
                }
                return global::Refit.GeneratedRequestRunner.SendObservable<global::System.Net.Http.HttpResponseMessage, global::System.Net.Http.HttpResponseMessage>(
                    this.Client,
                    BuildRefitRequest,
                    refitSettings,
                    false,
                    false,
                    false,
                    global::System.Threading.CancellationToken.None);
            }
        }
    }
}
