//HintName: IGeneratedClient.g.cs
// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

namespace Refit.Implementation
{
    /// <summary>Contains generated Refit implementation types.</summary>
    internal partial class Generated
    {
        /// <summary>Generated Refit implementation for global::RefitGeneratorTest.IGeneratedClient.</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("InterfaceStubGeneratorV2", "11.0.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        [global::System.Diagnostics.DebuggerNonUserCode]
        [global::RefitInternalGenerated.PreserveAttribute]
        [global::System.Reflection.Obfuscation(Exclude=true)]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        private sealed class RefitGeneratorTestIGeneratedClient
            : global::RefitGeneratorTest.IGeneratedClient
        {
            /// <summary>The request builder used to create Refit method delegates.</summary>
            private readonly global::Refit.IRequestBuilder? _requestBuilder;

            /// <summary>The settings used by this generated Refit implementation.</summary>
            private readonly global::Refit.RefitSettings _settings;

            /// <summary>Gets the HTTP client used by this generated Refit implementation.</summary>
            public global::System.Net.Http.HttpClient Client { get; }

            /// <summary>Initializes a new instance of the RefitGeneratorTestIGeneratedClient class.</summary>
            /// <param name="client">The HTTP client used by the generated implementation.</param>
            /// <param name="requestBuilder">The request builder used to create Refit method delegates.</param>
            public RefitGeneratorTestIGeneratedClient(global::System.Net.Http.HttpClient client, global::Refit.IRequestBuilder requestBuilder)
            {
                Client = client;
                _requestBuilder = requestBuilder;
                _settings = requestBuilder.Settings;
            }

            /// <inheritdoc />
            public async global::System.Threading.Tasks.Task<string> Get<T>()
                where T : unmanaged
            {
                var refitArguments = global::System.Array.Empty<object>();
                var refitRequestBuilder = _requestBuilder ?? throw new global::System.InvalidOperationException("This generated Refit method requires a request builder.");
                var refitFunc = refitRequestBuilder.BuildRestResultFuncForMethod("Get", global::System.Array.Empty<global::System.Type>(), new global::System.Type[] { typeof(T) } );

                return await ((global::System.Threading.Tasks.Task<string>)refitFunc(this.Client, refitArguments)).ConfigureAwait(false);
            }
        }
    }
}
