<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <IsPackable>false</IsPackable>
    <PublishAot Condition="'$(RuntimeIdentifier)' != ''">true</PublishAot>
    <WarningsAsErrors>$(WarningsAsErrors);IL2026;IL3050</WarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../Refit/Refit.csproj" />
    <ProjectReference Include="../../../../Refit.Testing/Refit.Testing.csproj" />
    <ProjectReference Include="../../../../InterfaceStubGenerator.Roslyn48/InterfaceStubGenerator.Roslyn48.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <Compile Include="../../Common/*.cs" Link="Common/%(Filename)%(Extension)" />
    <Compile Include="../../GettingStarted/Person.cs" Link="Person.cs" />
  </ItemGroup>
</Project>
