using System.Net.Http;
#if NET8_0_OR_GREATER
using System.Diagnostics.CodeAnalysis;
#endif

namespace Refit
{
    /// <summary>
    /// Defines a method for creating a delegate that executes a REST API method with the specified parameters and
    /// returns the result.
    /// </summary>
    /// <remarks>The returned delegate can be used to invoke a REST API method dynamically, given an HTTP
    /// client and an array of arguments. This interface is typically used by code generation or dynamic proxy libraries
    /// to construct method invokers at runtime. Implementations may use reflection and may require referenced types to
    /// be preserved when trimming assemblies.</remarks>
    public interface IRequestBuilder
    {
        /// <summary>
        /// Builds a delegate that executes the specified REST method using the provided HTTP client and arguments.
        /// </summary>
        /// <remarks>The returned delegate uses reflection to invoke the specified method and may require
        /// referenced interfaces and data transfer objects (DTOs) to be preserved when trimming assemblies. This method
        /// is typically used to dynamically generate REST API client calls at runtime.</remarks>
        /// <param name="methodName">The name of the interface method to generate the REST call delegate for. Must correspond to a method defined
        /// on the target interface.</param>
        /// <param name="parameterTypes">An array of parameter types for the target method, or null to infer from the method signature. The order
        /// must match the method's parameter list if specified.</param>
        /// <param name="genericArgumentTypes">An array of generic argument types to use when constructing a generic method, or null if the method is not
        /// generic.</param>
        /// <returns>A delegate that takes an HttpClient and an array of argument values, and returns the result of invoking the
        /// specified REST method. The return type matches the method's declared return type.</returns>
#if NET8_0_OR_GREATER
        [RequiresUnreferencedCode("Refit uses reflection to analyze interface methods. Ensure referenced interfaces and DTOs are preserved when trimming.")]
#endif
        Func<HttpClient, object[], object?> BuildRestResultFuncForMethod(
            string methodName,
            Type[]? parameterTypes = null,
            Type[]? genericArgumentTypes = null
        );
    }

    /// <summary>
    /// Defines a generic contract for building requests with a specified result type.
    /// </summary>
    /// <typeparam name="T">The type of the result produced by the request builder.</typeparam>
    public interface IRequestBuilder<T> : IRequestBuilder { }

    /// <summary>
    /// Provides static methods for creating request builders for Refit interface types. This class enables the
    /// generation of strongly-typed HTTP client implementations based on interface definitions and optional settings.
    /// </summary>
    /// <remarks>Request builders generated by this class use reflection to analyze the provided interface
    /// type and create implementations for HTTP API calls. When using trimming or linking, ensure that referenced
    /// interfaces and data transfer objects are preserved, as reflection is required for correct operation. All members
    /// of this class are thread-safe and can be used concurrently across multiple threads.</remarks>
    public static class RequestBuilder
    {
        static readonly RequestBuilderFactory PlatformRequestBuilderFactory = new();

        /// <summary>
        /// Creates an HTTP request builder for the specified interface type.
        /// </summary>
        /// <remarks>Use this method to obtain a request builder for a given API interface, typically for
        /// advanced scenarios such as custom client generation or integration with dependency injection. The returned
        /// builder can be used to create HTTP requests corresponding to the methods defined on the interface.</remarks>
        /// <typeparam name="T">The interface type that defines the HTTP API methods to be implemented by the request builder. Must be an
        /// interface.</typeparam>
        /// <param name="settings">The Refit settings to use for configuring the request builder. May be null to use default settings.</param>
        /// <returns>An instance of IRequestBuilder T that can be used to construct HTTP requests for the specified interface
        /// type.</returns>
#if NET8_0_OR_GREATER
        public static IRequestBuilder<T> ForType< [
            DynamicallyAccessedMembers(
                DynamicallyAccessedMemberTypes.PublicMethods |
                DynamicallyAccessedMemberTypes.NonPublicMethods
            )] T >(RefitSettings? settings) =>
            PlatformRequestBuilderFactory.Create<T>(settings);
#else
        public static IRequestBuilder<T> ForType<T>(RefitSettings? settings) =>
            PlatformRequestBuilderFactory.Create<T>(settings);
#endif

        /// <summary>
        /// Creates a request builder for the specified type, enabling the construction of requests targeting members of
        /// that type.
        /// </summary>
        /// <typeparam name="T">The type for which to create the request builder. This type's methods will be available for request
        /// construction.</typeparam>
        /// <returns>An object that can be used to build requests for the specified type.</returns>
#if NET8_0_OR_GREATER
        public static IRequestBuilder<T> ForType< [
            DynamicallyAccessedMembers(
                DynamicallyAccessedMemberTypes.PublicMethods |
                DynamicallyAccessedMemberTypes.NonPublicMethods
            )] T >() =>
            PlatformRequestBuilderFactory.Create<T>(null);
#else
        public static IRequestBuilder<T> ForType<T>() =>
            PlatformRequestBuilderFactory.Create<T>(null);
#endif

        /// <summary>
        /// Creates an implementation of the specified Refit interface for making HTTP requests.
        /// </summary>
        /// <remarks>The returned IRequestBuilder uses reflection to analyze the provided interface type.
        /// When using trimming or linking, ensure that all referenced interfaces and data transfer objects are
        /// preserved to avoid runtime errors.</remarks>
        /// <param name="refitInterfaceType">The interface type that defines the HTTP API contract. Must be a non-generic interface decorated with Refit
        /// attributes.</param>
        /// <param name="settings">Optional settings to customize the behavior of the generated request builder. If null, default settings are
        /// used.</param>
        /// <returns>An IRequestBuilder instance that can be used to construct HTTP requests for the specified interface.</returns>
#if NET8_0_OR_GREATER
        [RequiresUnreferencedCode("Refit uses reflection to analyze interface methods. Ensure referenced interfaces and DTOs are preserved when trimming.")]
        public static IRequestBuilder ForType(
            [DynamicallyAccessedMembers(
                DynamicallyAccessedMemberTypes.PublicMethods |
                DynamicallyAccessedMemberTypes.NonPublicMethods
            )] Type refitInterfaceType,
            RefitSettings? settings
        )
#else
        public static IRequestBuilder ForType(
            Type refitInterfaceType,
            RefitSettings? settings
        )
#endif
        {
            return new CachedRequestBuilderImplementation(
                new RequestBuilderImplementation(refitInterfaceType, settings)
            );
        }

        /// <summary>
        /// Creates an instance of an IRequestBuilder for the specified Refit interface type.
        /// </summary>
        /// <remarks>The specified interface type must be decorated with Refit attributes to define the
        /// API endpoints. If trimming is enabled, ensure that all referenced interfaces and data transfer objects are
        /// preserved, as reflection is used to analyze the interface methods.</remarks>
        /// <param name="refitInterfaceType">The interface type that defines the Refit API contract. Must be a non-generic interface decorated with Refit
        /// attributes.</param>
        /// <returns>An IRequestBuilder instance that can be used to construct HTTP requests for the specified interface type.</returns>
#if NET8_0_OR_GREATER
        [RequiresUnreferencedCode("Refit uses reflection to analyze interface methods. Ensure referenced interfaces and DTOs are preserved when trimming.")]
#endif
        public static IRequestBuilder ForType(Type refitInterfaceType) =>
            ForType(refitInterfaceType, null);
    }
}
