name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  productNamespacePrefix: "Refit"

jobs:
  build:
    uses: reactiveui/actions-common/.github/workflows/workflow-common-setup-and-build.yml@main
    with:
      productNamespacePrefix: "Refit"
      srcFolder: "./"
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
